product/hcm/Fap.Hcm.Web/Areas/SelfService/Controllers/MssController.cs
using System;
using Fap.Core.Extensions;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Fap.AspNetCore.Infrastructure;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.DependencyInjection;
using Fap.Hcm.Service.Organization;
using Fap.Core.Infrastructure.Metadata;
using Fap.Hcm.Web.Models;
using NPOI.SS.Formula.Functions;

namespace Fap.Hcm.Web.Areas.SelfService.Controllers
{
    [Area("SelfService")]
    public class MssController : FapController
    {
        private readonly IOrganizationService _organizationService;
        public MssController(IServiceProvider serviceProvider) : base(serviceProvider)
        {
            _organizationService = serviceProvider.GetService<IOrganizationService>();
        }
        /// <summary>
        /// 部门员工信息
        /// </summary>
        /// <returns></returns>
        public IActionResult DeptEmployee()
        {
            ViewBag.EmpStatus = _dbContext.Dictionarys("EmpStatus");
            IEnumerable<FapTable> empChilds = _dbContext.Tables(t => t.TableCategory == "EmpSub");//||t.TableCategory=="EmpBiz");
            var gvms = empChilds.Select(t => new GridViewModel { TableLabel = t.TableComment, TableName = t.TableName, Condition = "EmpUid='" + _applicationContext.EmpUid + "'" });
            ViewBag.SubInfo = gvms.ToJson();
            var deptUids = _organizationService.GetDominationDepartment().Select(d => $"'{d.Fid}'");
            var model = GetJqGridModel("Employee", qs =>
            {
                qs.GlobalWhere = deptUids.Any() ? $"DeptUid in({string.Join(',', deptUids)})" : "1=2";
            });
            return View(model);
        }
        public IActionResult DeptEmployeeSelector()
        {
            var deptUids = _organizationService.GetDominationDepartment().Select(d => $"'{d.Fid}'");
            var model = GetJqGridModel("Employee",qs=>
            {
                qs.GlobalWhere = deptUids.Any() ? $"DeptUid in({string.Join(',', deptUids)})" : "1=2";
            });
            return PartialView(model);
        }
        /// <summary>
        /// 部门周报日报月报
        /// </summary>
        /// <returns></returns>
        public IActionResult EmpReport(string empUid)
        {
            var model = this.GetJqGridModel("EssReport", (q) =>
            {
                q.GlobalWhere = $"EmpUid=@EmpUid";
                q.AddParameter("EmpUid", empUid);
            });
            return PartialView(model);
        }
        /// <summary>
        /// 部门日历
        /// </summary>
        /// <returns></returns>
        public IActionResult DeptCalendar()
        {
            return View();
        }


    }
}

product/hcm/Fap.Hcm.Web/Controllers/ComponentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using Fap.Core.Extensions;
using Fap.AspNetCore.Infrastructure;
using Microsoft.AspNetCore.Mvc;
using Fap.Core.Annex;
using Fap.Core.Infrastructure.Model;
using System.IO;
using Fap.Core.Infrastructure.Metadata;
using System.Text.RegularExpressions;
using Fap.Core.Infrastructure.Domain;
using Fap.Core.DataAccess;
using Newtonsoft.Json.Linq;
using Fap.AspNetCore.ViewModel;
using Fap.AspNetCore.Controls;
using Fap.Core.Rbac.Model;
using Fap.Core.Infrastructure.Query;
using Dapper;
using Fap.AspNetCore.Controls.DataForm;
using Fap.Hcm.Web.Models;
using Ardalis.GuardClauses;
using Microsoft.Extensions.Logging;
using Microsoft.AspNetCore.Authorization;
//using NPOI.SS.Formula.Functions;

namespace Fap.Hcm.Web.Controllers
{
    public class ComponentController : FapController
    {
        private readonly IFapFileService _fapFileService;
        private readonly ILogger _logger;
        public ComponentController(IServiceProvider serviceProvider, IFapFileService fapFileService) : base(serviceProvider)
        {
            _fapFileService = fapFileService;
            _logger = _loggerFactory.CreateLogger<ComponentController>();
        }
        [AllowAnonymous]
        public FileResult Photo(string fid)
        {
            if (fid.IsMissing())
            {
                return File("~/Content/avatars/profile-pic.jpg", "image/png");
            }
            FapAttachment attachment = _fapFileService.DownloadOneFileByBid(fid, out Stream stream);
            if (attachment == null || stream == null)
            {
                return File("~/Content/avatars/profile-pic.jpg", "image/png");
            }
            else
            {
                return File(stream, attachment.FileType);
            }

        }
        public IActionResult Guide(string nav)
        {            
            var guide= _dbContext.QueryFirstOrDefault<FapGuide>("select * from FapGuide where Navigation=@Nav", new DynamicParameters(new { Nav = nav }));
            if (guide==null)
            {
                guide = new FapGuide { Navigation = nav,Guide="暂无，尽快奉上。" };
                _dbContext.Insert(guide);
            }
            return PartialView(guide);
        }

        //同时表单数据也会传递过来，条件设置参数同Dapper
        //例如：TableName=@Entity,Entity为form传过来的参数
        // GET: /Component/GridReference
        /// <summary>
        /// 表格参照
        /// </summary>
        /// <returns></returns>
        public IActionResult GridReference(string fid, int isSearch = 0)
        {
            string refcondition = string.Empty;
            _platformDomain.ColumnSet.TryGetValue(fid, out FapColumn fc);
            //fc.RefCondition替换参数的值
            if (fc.RefCondition.IsPresent())
            {
                refcondition = fc.RefCondition;
                string fieldName = string.Empty;
                //
                Regex regex = new Regex(FapPlatformConstants.VariablePattern, RegexOptions.IgnoreCase);
                var mat = regex.Matches(fc.RefCondition);
                foreach (Match item in mat)
                {

                    fieldName = item.ToString().Substring(2, item.ToString().Length - 3);
                    if (!Request.Query.ContainsKey(fieldName))
                    {
                        fieldName = item.ToString();
                        if (fieldName.EqualsWithIgnoreCase(FapDbConstants.CurrentEmployee))
                        {
                            refcondition = refcondition.Replace(item.ToString(), _applicationContext.EmpUid,StringComparison.OrdinalIgnoreCase);
                        }
                        else if (fieldName.EqualsWithIgnoreCase(FapDbConstants.CurrentUser))
                        {
                            refcondition = refcondition.Replace(item.ToString(), _applicationContext.UserName, StringComparison.OrdinalIgnoreCase);
                        }
                        else if (fieldName.EqualsWithIgnoreCase(FapDbConstants.CurrentDept))
                        {
                            refcondition = refcondition.Replace(item.ToString(), _applicationContext.DeptUid, StringComparison.OrdinalIgnoreCase);
                        }
                        else if (fieldName.EqualsWithIgnoreCase(FapDbConstants.CurrentDeptCode))
                        {
                            //OrgDept dept = da.Get<OrgDept>(_session.AcSession.Employee.DeptUid);
                            refcondition = refcondition.Replace(item.ToString(), _applicationContext.DeptCode, StringComparison.OrdinalIgnoreCase);
                        }
                    }
                    else
                    {
                        refcondition = refcondition.Replace(item.ToString(), Request.Query[fieldName].ToString(), StringComparison.OrdinalIgnoreCase);
                    }
                }
            }
            List<string> refCols = new List<string>();
            List<string> frmCols = new List<string>();

            //参照名称
            List<string> refRefCols = new List<string>();
            List<string> frmRefCols = new List<string>();
            if (fc.RefReturnMapping.IsPresent())
            {
                JArray arrMapping = JArray.Parse(fc.RefReturnMapping);
                foreach (JObject item in arrMapping)
                {
                    string refCol = item.GetValue("RefCol",StringComparison.OrdinalIgnoreCase).ToString();
                    refCols.Add(refCol);
                    string frmCol = item.GetValue("FrmCol", StringComparison.OrdinalIgnoreCase).ToString();
                    frmCols.Add(frmCol);
                    string refTable = fc.RefTable;
                    //针对参照列的特殊处理
                    var refColumn = _dbContext.Column(refTable, refCol);
                    var frmColumn = _dbContext.Column(fc.TableName, frmCol);
                    if (refColumn != null && frmColumn != null)
                    {
                        if (refColumn.CtrlType == FapColumn.CTRL_TYPE_REFERENCE && frmColumn.CtrlType == FapColumn.CTRL_TYPE_REFERENCE)
                        {
                            refRefCols.Add(refColumn.ColName + "MC");
                            frmRefCols.Add(frmColumn.ColName + "MC");
                        }
                    }
                }
            }
            string cols = "Id," + (!string.IsNullOrWhiteSpace(fc.RefID) ? fc.RefID + "," : "") + (!string.IsNullOrWhiteSpace(fc.RefCode) ? fc.RefCode + "," : "") + fc.RefName + "," + (!string.IsNullOrWhiteSpace(fc.RefCols) ? fc.RefCols : "");
            if (refCols.Count > 0)
            {
                cols = cols.TrimEnd(',') + "," + string.Join(",", refCols);
            }
            else
            {
                cols = cols.TrimEnd(',');
            }
            string[] colList = cols.Split(',');
            //注释掉人员权限，如果需要权限直接在条件中写
            //人员加权限
            if (fc.RefTable.EqualsWithIgnoreCase("employee") && !_applicationContext.IsAdministrator)
            {
                //包含权限设置
                if (refcondition.IsPresent() && !refcondition.Contains(FapDbConstants.EmployeeNoPower, StringComparison.OrdinalIgnoreCase))
                {
                    string where = "DeptUid in(" + FapPlatformConstants.DepartmentAuthority + ")";
                    refcondition += " and " + where;
                }

            }
            JqGridViewModel model = this.GetJqGridModel(fc.RefTable, (q) =>
            {
                q.GlobalWhere = refcondition.Replace(FapDbConstants.EmployeeNoPower, "", StringComparison.OrdinalIgnoreCase);
                q.QueryCols = string.Join(",", colList.Distinct());

            });
            model.JqgridId = $"ref{model.JqgridId}";
            if (isSearch == 1)
            {
                model.IsMulti = true;
            }
            if (refRefCols.Any())
            {
                refCols.AddRange(refRefCols);
                frmCols.AddRange(frmRefCols);
            }

            model.TempData.Add("refid", fc.RefID);
            model.TempData.Add("refcode", fc.RefCode);
            model.TempData.Add("refname", fc.RefName);
            model.TempData.Add("frmCols", string.Join(",", frmCols));
            model.TempData.Add("refCols", string.Join(",", refCols));
            return View(model);

        }
        /// <summary>
        /// 树表参照
        /// </summary>
        /// <returns></returns>
        public IActionResult TreeGridReference()
        {
            return View();
        }
        /// <summary>
        /// 树参照
        /// </summary>
        /// <returns></returns>
        public IActionResult TreeReference(string fid, int isSearch = 0)
        {
            string refcondition = string.Empty;
            _platformDomain.ColumnSet.TryGetValue(fid, out FapColumn fc);
            //fc.RefCondition替换参数的值
            if (fc.RefCondition.IsPresent())
            {
                refcondition = fc.RefCondition;
                string fieldName = string.Empty;
                //
                Regex regex = new Regex(FapPlatformConstants.VariablePattern, RegexOptions.IgnoreCase);
                var mat = regex.Matches(fc.RefCondition);
                foreach (Match item in mat)
                {
                    fieldName = item.ToString().Substring(2, item.ToString().Length - 3);
                    refcondition = refcondition.Replace(item.ToString(), Request.Query[fieldName].ToString(), StringComparison.OrdinalIgnoreCase);
                }
            }

            string icon = "icon-folder  ace-icon fa fa-folder blue";

            List<string> refCols = new List<string>();
            List<string> frmCols = new List<string>();
            //参照名称
            List<string> refRefCols = new List<string>();
            List<string> frmRefCols = new List<string>();
            List<string> refMcSqls = new List<string>();
            if (fc.RefReturnMapping.IsPresent())
            {

product/hcm/Fap.Hcm.Web/Areas/SelfService/Views/Mss/DeptEmployee.cshtml
@model Fap.AspNetCore.ViewModel.JqGridViewModel
@{
    //在岗状态
    IEnumerable<Fap.Core.Infrastructure.Metadata.FapDict> empStatus = ViewBag.EmpStatus;
}
<title><fap-multilang lang-key="empinfo_index_title" default-content="员工档案"></fap-multilang>    </title>

<link href="~/Content/css/bootstrap-timeline.css" rel="stylesheet" />

<style>
    .billskin .layui-layer-btn0 {
        background-color: #d15b47 !important;
        border-color: #428bca;
    }
</style>
<div class="row">
    <div class="col-xs-12">
        <div id="widget-box-orgdept" class="widget-box">
            <div class="widget-header widget-header-flat">
                <h4 class="widget-title">
                    <fap-multilang lang-key="empinfo_index_title" default-content="员工档案"></fap-multilang>
                </h4>
                <div class="widget-toolbar">
                    <a href="#" data-action="fullscreen" class="orange2">
                        <i class="ace-icon fa fa-expand"></i>
                    </a>
                </div>
                <div class="widget-toolbar">
                    <label>
                        <input name="chkshowpartjob" id="chkshowpartjob" type="checkbox" class="ace" />
                        <span class="lbl"> 兼职</span>
                    </label>
                    <label>
                        <input type="checkbox" id="chkphoto" class="ace" />
                        <span class="lbl">
                            <fap-multilang lang-key="mss_employees_page_photo" default-content="照片"></fap-multilang>
                        </span>
                    </label>
                </div>

                <div class="widget-toolbar">
                    <fap-button id="btnSchedule" btn-tag="link" content="排班" icon-before="fa fa-calendar-check-o blue" class-name="info"></fap-button>
                    <fap-button id="btnSubInfo" btn-tag="link" content="附属信息" icon-before="fa fa-paperclip blue" class-name="info"></fap-button>
                    <fap-button id="btnEmployeeHistory" btn-tag="link" content="历史" icon-before="fa fa-history blue" class-name="info"></fap-button>
                </div>
                <div class="widget-toolbar">
                    <fap-button id="btnTmCardRecord" btn-tag="link" content="考勤打卡" icon-before="fa fa-credit-card blue" class-name="info"></fap-button>
                    <fap-button id="btnEmpReport" btn-tag="link" content="日报周报" icon-before="fa fa-calendar-check-o blue" class-name="info"></fap-button>
                </div>
            </div>
            <div class="widget-body">
                <!-- #section:custom/widget-box.toolbox -->
                <div class="widget-main">
                    <fap-grid id="employee" grid-model="Model" 
                              auto-width="true" on-select-row="ShowPhoto(rowid)" multi-box-only="true" multi-select="true"  register-authority="false" shrink-fit="false"></fap-grid>
                </div>
            </div>
        </div>
        <!-- /section:elements.tab -->
        <div id="right-menu" class="modal aside" data-body-scroll="false" data-offset="true" data-placement="right" data-fixed="true" data-backdrop="invisible" tabindex="-1">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header no-padding">
                        <div class="table-header">
                            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">
                                <span class="white">&times;</span>
                            </button>
                            <fap-multilang lang-key="department" default-content="部门"></fap-multilang>
                        </div>
                    </div>

                    <div class="modal-body">
                        <div id="treeDeptDiv" class="widget-main ">                          
                            <div>
                                <span><fap-multilang lang-key="employee_status" default-content="在岗状态"></fap-multilang>: &nbsp;</span>
                                <div>
                                    @foreach (var item in empStatus)
                                    {
                                        bool chk = item.Code == "Current";
                                        <label>
                                            <input data-ctrl="empstatus" name="form-field-checkbox-empstatus" value="@item.Code" type="checkbox" fap-checked="chk" class="ace" />
                                            <span class="lbl"> @item.Name</span>
                                        </label>
                                    }
                                </div>
                            </div>
                            <div class="scrollable">
                                <fap-tree id="orgdept" is-async="true" get-url="/SelfService/Api/DominationDepartment"></fap-tree>
                            </div>
                        </div>
                    </div>
                </div><!-- /.modal-content -->

                <button class="aside-trigger btn btn-purple btn-app btn-xs ace-settings-btn" data-target="#right-menu" data-toggle="modal" type="button">
                    <i data-icon1="fa-sitemap" data-icon2="fa-minus" class="ace-icon fa fa-sitemap bigger-110 icon-only"></i>
                </button>
            </div><!-- /.modal-dialog -->
        </div>

    </div>
</div>

<script> 
    var scripts = [null, "/Content/js/jquery-migrate-1.1.0.js", "/Content/js/jquery.jqprint-0.3.js", "/Scripts/Employee/EmpIndex.js?v=1",  null];
    $('.page-content-area').ace_ajax('loadScripts', scripts, function () {
        jQuery(function ($) {
            $('.modal.aside').ace_aside();
            $(document).one('ajaxloadstart.page', function (e) {
                $('#tree-orgdept').jstree("destroy");
                $('.modal.aside').remove();
                $(window).off('.aside');
            })         
            //排班
            $("#btnSchedule").on(ace.click_event, function () {
                var ret = getSelectedRow("grid-employee");
                if (ret == null) {
                    return;
                }
                bootboxWindow($.lang("time_schedule","排班"),basePath+"/Time/Manage/ScheduleInfo/"+ret.Fid)
            });            

            $("#btnSubInfo").on(ace.click_event, function () {
                var rowData = getSelectedRow("grid-employee");
                if (rowData === null) {
                    return;
                }               
                var dialog = bootbox.dialog({
                    title: $.lang("appertain_info", "附属信息"),
                    size: 'large',
                    message: '<p><i class="fa fa-spin fa-spinner"></i> Loading...</p>',
                    buttons: {
                        cancel: {
                            label: "关闭", className: "btn-default"
                        }
                    }
                });
                var data = { "gridViews": @Html.Raw(ViewBag.SubInfo)};
                $.each(data.gridViews, function (i, v) {
                    v.defaultValues.push({ "Field": "EmpUid", "Value": rowData.Fid });
                    v.defaultValues.push({ "Field": "EmpUidMC", "Value": rowData.EmpName });
                    v.defaultValues.push({ "Field": "EmpCode", "Value": rowData.EmpCode });
                });
                dialog.init(function () {
                    var url = "@Html.Raw(Url.Action("MultiDataGrid", "Component", new { area = "" }))";
                    $.post(url, data, function (ev) {
                        dialog.find('.bootbox-body').html(ev);
                    })
                });
            });
            //历史修改信息
            $("#btnEmployeeHistory").on(ace.click_event, function () {
                var rowData = getSelectedRow("grid-employee");
                if (rowData === null) {
                    return;
                }
                if (rowData.IsMainJob == 0) {
                    $.msg("此条信息为兼职信息，请选择主职信息查看！");
                    return;
                }
                bootboxWindow($.lang("employee_history", "历史追溯"),
                    basePath + "/Component/DataHistory", null, { bn: 'Employee', fid: rowData.Fid });               

            });
            $("#btnEmpReport").on(ace.click_event, function () {
                var rowData = getSelectedRow("grid-employee");
                if (rowData === null) {
                    return;
                }
                bootboxWindow($.lang("day_report", "日报周报"),
                    basePath + "/SelfService/Mss/EmpReport", null, { empUid: rowData.Fid });          
            })
            $("#btnTmCardRecord").on(ace.click_event, function () {
                var rowData = getSelectedRow("grid-employee");
                if (rowData === null) {
                    return;
                }
                bootboxWindow($.lang("time_card_record", "考勤打卡"),
                    basePath + "/Time/Manage/EmpCardRecord", null, { empUid: rowData.Fid });
            })
            //部门变化事件，加载人员信息
            $('#tree-orgdept').on("changed.jstree", function (e, data) {
                if (data && data.selected && data.selected.length) {
                    var deptid = data.selected[0];
                    //获取所有子Fid
                    var childs = data.node.children_d;
                    var selids = childs.concat(deptid);
                    //筛选有权限的节点
                    var treeDept = $('#tree-orgdept').jstree(true);
                    var sels = $.grep(selids, function (d, i) {                        
                        return treeDept.get_node(d).data.isDept === 1;

                    });
                    var filter = { "groupOp": "AND" };
                    var rules = [];
                    rules.push({ "field": "DeptUid", "op": "in", "data": sels.join(',') });                    
                    //在岗状态
                    var selEmpStatus = [];
                    $("input[data-ctrl=empstatus]").each(function () {
                        if ($(this).is(':checked')) {
                            selEmpStatus.push($(this).val());
                        }
                    })
                    if (selEmpStatus != '')
                    {
                        rules.push({ "field": "EmpStatus", "op": "in", "data": selEmpStatus.join(',') });
                    }
                    //兼职
                    if ($('#chkshowpartjob').get(0).checked) {
                        //兼职打勾的话，去掉职位类型条件
                    } else {
                        //默认显示主职
                        rules.push({ "field": "IsMainJob", "op": "eq", "data": 1 });
                    }
                    filter.rules = rules;
                    reloadGrid("grid-employee", { filters: JSON.stringify(filter) });

                }
            });

        })
    });
</script>

product/hcm/Fap.Hcm.Web/Areas/SelfService/Views/Mss/DeptEmployeeSelector.cshtml
@model Fap.AspNetCore.ViewModel.JqGridViewModel

<fap-grid id="@Model.JqgridId" grid-model="Model" auto-width="true" wrapper="modal-body" view-records="true"  multi-select="true" shrink-fit="false"></fap-grid>

product/hcm/Fap.Hcm.Web/Areas/SelfService/Views/Mss/EmpReport.cshtml
@model Fap.AspNetCore.ViewModel.JqGridViewModel

<fap-grid id="essreport" grid-model="Model" wrapper="modal-body" register-authority="false" view-records="true" shrink-fit="false"></fap-grid>