product/hcm/Fap.Hcm.Web/Controllers/ComponentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using Fap.Core.Extensions;
using Fap.AspNetCore.Infrastructure;
using Microsoft.AspNetCore.Mvc;
using Fap.Core.Annex;
using Fap.Core.Infrastructure.Model;
using System.IO;
using Fap.Core.Infrastructure.Metadata;
using System.Text.RegularExpressions;
using Fap.Core.Infrastructure.Domain;
using Fap.Core.DataAccess;
using Newtonsoft.Json.Linq;
using Fap.AspNetCore.ViewModel;
using Fap.AspNetCore.Controls;
using Fap.Core.Rbac.Model;
using Fap.Core.Infrastructure.Query;
using Dapper;
using Fap.AspNetCore.Controls.DataForm;
using Fap.Hcm.Web.Models;
using Ardalis.GuardClauses;
using Microsoft.Extensions.Logging;
using Microsoft.AspNetCore.Authorization;
//using NPOI.SS.Formula.Functions;

namespace Fap.Hcm.Web.Controllers
{
    public class ComponentController : FapController
    {
        private readonly IFapFileService _fapFileService;
        private readonly ILogger _logger;
        public ComponentController(IServiceProvider serviceProvider, IFapFileService fapFileService) : base(serviceProvider)
        {
            _fapFileService = fapFileService;
            _logger = _loggerFactory.CreateLogger<ComponentController>();
        }
        [AllowAnonymous]
        public FileResult Photo(string fid)
        {
            if (fid.IsMissing())
            {
                return File("~/Content/avatars/profile-pic.jpg", "image/png");
            }
            FapAttachment attachment = _fapFileService.DownloadOneFileByBid(fid, out Stream stream);
            if (attachment == null || stream == null)
            {
                return File("~/Content/avatars/profile-pic.jpg", "image/png");
            }
            else
            {
                return File(stream, attachment.FileType);
            }

        }
        public IActionResult Guide(string nav)
        {            
            var guide= _dbContext.QueryFirstOrDefault<FapGuide>("select * from FapGuide where Navigation=@Nav", new DynamicParameters(new { Nav = nav }));
            if (guide==null)
            {
                guide = new FapGuide { Navigation = nav,Guide="暂无，尽快奉上。" };
                _dbContext.Insert(guide);
            }
            return PartialView(guide);
        }

        //同时表单数据也会传递过来，条件设置参数同Dapper
        //例如：TableName=@Entity,Entity为form传过来的参数
        // GET: /Component/GridReference
        /// <summary>
        /// 表格参照
        /// </summary>
        /// <returns></returns>
        public IActionResult GridReference(string fid, int isSearch = 0)
        {
            string refcondition = string.Empty;
            _platformDomain.ColumnSet.TryGetValue(fid, out FapColumn fc);
            //fc.RefCondition替换参数的值
            if (fc.RefCondition.IsPresent())
            {
                refcondition = fc.RefCondition;
                string fieldName = string.Empty;
                //
                Regex regex = new Regex(FapPlatformConstants.VariablePattern, RegexOptions.IgnoreCase);
                var mat = regex.Matches(fc.RefCondition);
                foreach (Match item in mat)
                {

                    fieldName = item.ToString().Substring(2, item.ToString().Length - 3);
                    if (!Request.Query.ContainsKey(fieldName))
                    {
                        fieldName = item.ToString();
                        if (fieldName.EqualsWithIgnoreCase(FapDbConstants.CurrentEmployee))
                        {
                            refcondition = refcondition.Replace(item.ToString(), _applicationContext.EmpUid,StringComparison.OrdinalIgnoreCase);
                        }
                        else if (fieldName.EqualsWithIgnoreCase(FapDbConstants.CurrentUser))
                        {
                            refcondition = refcondition.Replace(item.ToString(), _applicationContext.UserName, StringComparison.OrdinalIgnoreCase);
                        }
                        else if (fieldName.EqualsWithIgnoreCase(FapDbConstants.CurrentDept))
                        {
                            refcondition = refcondition.Replace(item.ToString(), _applicationContext.DeptUid, StringComparison.OrdinalIgnoreCase);
                        }
                        else if (fieldName.EqualsWithIgnoreCase(FapDbConstants.CurrentDeptCode))
                        {
                            //OrgDept dept = da.Get<OrgDept>(_session.AcSession.Employee.DeptUid);
                            refcondition = refcondition.Replace(item.ToString(), _applicationContext.DeptCode, StringComparison.OrdinalIgnoreCase);
                        }
                    }
                    else
                    {
                        refcondition = refcondition.Replace(item.ToString(), Request.Query[fieldName].ToString(), StringComparison.OrdinalIgnoreCase);
                    }
                }
            }
            List<string> refCols = new List<string>();
            List<string> frmCols = new List<string>();

            //参照名称
            List<string> refRefCols = new List<string>();
            List<string> frmRefCols = new List<string>();
            if (fc.RefReturnMapping.IsPresent())
            {
                JArray arrMapping = JArray.Parse(fc.RefReturnMapping);
                foreach (JObject item in arrMapping)
                {
                    string refCol = item.GetValue("RefCol",StringComparison.OrdinalIgnoreCase).ToString();
                    refCols.Add(refCol);
                    string frmCol = item.GetValue("FrmCol", StringComparison.OrdinalIgnoreCase).ToString();
                    frmCols.Add(frmCol);
                    string refTable = fc.RefTable;
                    //针对参照列的特殊处理
                    var refColumn = _dbContext.Column(refTable, refCol);
                    var frmColumn = _dbContext.Column(fc.TableName, frmCol);
                    if (refColumn != null && frmColumn != null)
                    {
                        if (refColumn.CtrlType == FapColumn.CTRL_TYPE_REFERENCE && frmColumn.CtrlType == FapColumn.CTRL_TYPE_REFERENCE)
                        {
                            refRefCols.Add(refColumn.ColName + "MC");
                            frmRefCols.Add(frmColumn.ColName + "MC");
                        }
                    }
                }
            }
            string cols = "Id," + (!string.IsNullOrWhiteSpace(fc.RefID) ? fc.RefID + "," : "") + (!string.IsNullOrWhiteSpace(fc.RefCode) ? fc.RefCode + "," : "") + fc.RefName + "," + (!string.IsNullOrWhiteSpace(fc.RefCols) ? fc.RefCols : "");
            if (refCols.Count > 0)
            {
                cols = cols.TrimEnd(',') + "," + string.Join(",", refCols);
            }
            else
            {
                cols = cols.TrimEnd(',');
            }
            string[] colList = cols.Split(',');
            //注释掉人员权限，如果需要权限直接在条件中写
            //人员加权限
            if (fc.RefTable.EqualsWithIgnoreCase("employee") && !_applicationContext.IsAdministrator)
            {
                //包含权限设置
                if (refcondition.IsPresent() && !refcondition.Contains(FapDbConstants.EmployeeNoPower, StringComparison.OrdinalIgnoreCase))
                {
                    string where = "DeptUid in(" + FapPlatformConstants.DepartmentAuthority + ")";
                    refcondition += " and " + where;
                }

            }
            JqGridViewModel model = this.GetJqGridModel(fc.RefTable, (q) =>
            {
                q.GlobalWhere = refcondition.Replace(FapDbConstants.EmployeeNoPower, "", StringComparison.OrdinalIgnoreCase);
                q.QueryCols = string.Join(",", colList.Distinct());

            });
            model.JqgridId = $"ref{model.JqgridId}";
            if (isSearch == 1)
            {
                model.IsMulti = true;
            }
            if (refRefCols.Any())
            {
                refCols.AddRange(refRefCols);
                frmCols.AddRange(frmRefCols);
            }

            model.TempData.Add("refid", fc.RefID);
            model.TempData.Add("refcode", fc.RefCode);
            model.TempData.Add("refname", fc.RefName);
            model.TempData.Add("frmCols", string.Join(",", frmCols));
            model.TempData.Add("refCols", string.Join(",", refCols));
            return View(model);

        }
        /// <summary>
        /// 树表参照
        /// </summary>
        /// <returns></returns>
        public IActionResult TreeGridReference()
        {
            return View();
        }
        /// <summary>
        /// 树参照
        /// </summary>
        /// <returns></returns>
        public IActionResult TreeReference(string fid, int isSearch = 0)
        {
            string refcondition = string.Empty;
            _platformDomain.ColumnSet.TryGetValue(fid, out FapColumn fc);
            //fc.RefCondition替换参数的值
            if (fc.RefCondition.IsPresent())
            {
                refcondition = fc.RefCondition;
                string fieldName = string.Empty;
                //
                Regex regex = new Regex(FapPlatformConstants.VariablePattern, RegexOptions.IgnoreCase);
                var mat = regex.Matches(fc.RefCondition);
                foreach (Match item in mat)
                {
                    fieldName = item.ToString().Substring(2, item.ToString().Length - 3);
                    refcondition = refcondition.Replace(item.ToString(), Request.Query[fieldName].ToString(), StringComparison.OrdinalIgnoreCase);
                }
            }

            string icon = "icon-folder  ace-icon fa fa-folder blue";

            List<string> refCols = new List<string>();
            List<string> frmCols = new List<string>();
            //参照名称
            List<string> refRefCols = new List<string>();
            List<string> frmRefCols = new List<string>();
            List<string> refMcSqls = new List<string>();
            if (fc.RefReturnMapping.IsPresent())
            {

product/hcm/Fap.Hcm.Web/ViewComponents/CommonViewComponent.cs
using Dapper;
using Fap.AspNetCore.Model;
using Fap.Core.DataAccess;
using Fap.Core.Infrastructure.Domain;
using Fap.Core.Infrastructure.Model;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace Fap.Hcm.Web.ViewComponents
{
    /// <summary>
    /// 数据历史
    /// </summary>
    public class DataHistoryViewComponent : ViewComponent
    {
        private readonly IDbContext _dataAccessor;
        public DataHistoryViewComponent(IDbContext dataAccessor)
        {
            _dataAccessor = dataAccessor;
        }
        public async Task<IViewComponentResult> InvokeAsync(string bn, string fid)
        {
            var history = _dataAccessor.QueryDataHistory(bn, fid);
            return await Task.FromResult(View(history)).ConfigureAwait(false);
        }
    }
    public class QueryProgramViewComponent:ViewComponent
    {
        private readonly IDbContext _dataAccessor;
        private readonly IFapApplicationContext _applicationContext;
        public QueryProgramViewComponent(IDbContext dataAccessor, IFapApplicationContext appContext)
        {
            _dataAccessor = dataAccessor;
            _applicationContext = appContext;
        }
        public async Task<IViewComponentResult> InvokeAsync(string tn, string gid)
        {
            string where = " (Tablename=@TableName and UseEmployee=@UseEmployee) or IsGlobal=1 ";
            DynamicParameters param = new DynamicParameters();
            param.Add("TableName", tn);
            param.Add("UseEmployee", _applicationContext.EmpUid);
            var qPlist = _dataAccessor.QueryWhere<CfgQueryProgram>(where, param);
            ViewBag.GrdId = gid;
            ViewBag.Tn = tn;
            return await Task.FromResult(View(qPlist)).ConfigureAwait(false);
        }
    }
    public class ConditionEditorViewComponent : ViewComponent
    {
        public async Task<IViewComponentResult> InvokeAsync(string tableName)
        {
            ViewBag.TableName = tableName;
            return await Task.FromResult(View()).ConfigureAwait(false);
        }
    }
}

product/hcm/Fap.Hcm.Web/Views/Component/AttachmentInfo.cshtml
@using Fap.Core.Infrastructure.Model
@model   IEnumerable<FapAttachment>
@{
    Layout = null;
    int fileCount = 0;
    double Modelize = 0.0;
    string bid = "";
    if (Model.Any())
    {
        fileCount = Model.Count();
        Modelize = Math.Round(Model.Sum(f => f.FileSize) / 1024.0, 2);
        bid = Model.First().Bid;
    }
}

<script type="text/javascript">
    jQuery(function ($) {
        var $overflow = '';
        var colorbox_params = {
            rel: 'colorbox',
            reposition: true,
            scalePhotos: true,
            scrolling: false,
            photo: true,
            previous: '<i class="ace-icon fa fa-arrow-left"></i>',
            next: '<i class="ace-icon fa fa-arrow-right"></i>',
            close: '&times;',
            current: '{current} of {total}',
            maxWidth: '100%',
            maxHeight: '100%',
            showImage: true,  //显示图片  add by suncht
            onOpen: function () {
                $overflow = document.body.style.overflow;
                document.body.style.overflow = 'hidden';
            },
            onClosed: function () {
                document.body.style.overflow = $overflow;
            },
            onComplete: function () {
                $.colorbox.resize();
            }
        };

        $('.ace-thumbnails [data-rel="colorbox"]').colorbox(colorbox_params);
        $("#cboxLoadingGraphic").html("<i class='ace-icon fa fa-spinner orange fa-spin'></i>");//let's add a custom loading icon


        $(document).one('ajaxloadstart.page', function (e) {
            $('#colorbox, #cboxOverlay').remove();
        });
        $('[data-rel=tooltip]').tooltip();
        //预览
        $(".attached-file").on(ace.click_event, function (e) {
            e.preventDefault();

            var fid = $(this).data("filefid");
            $.get("@Url.Content("~/Core/Api/viewfile/")" + fid, function (data) {
                if (data.success) {
                    if (data.id == 'img') {
                        openNewWindow("@Url.Content("~/UploadFiles/View/")" + data.msg);
                    } else if (data.id == "0") {
                        $.msg($.lang("not_support_view","不支持预览"));
                    } else {
                        openNewWindow("@Url.Content("~/Content/Pdf/web/viewer.html")?file=/UploadFiles/View/" + data.msg);
                    }
                } else {
                    bootbox.alert(data.msg);
                }
            })
        })
        @*//删除
        $(".deletefile").on(ace.click_event, function (e) {
            debugger
            e.preventDefault();
            var fid = $(this).data("filefid");
            var df = $(this);
            bootbox.confirm("确定删除此附件?", function (result) {
                if (result) {
                    //
                    $.post("@Url.Content("~/Core/Api/deletefile/")", { key: fid }, function (rv) {
                        if (rv == "1") {
                            df.parent().parent().remove();
                        }
                    })
                }
            });
        })*@

    })
</script>


<div class="row">
    <div class="col-xs-12">
        <div>
            <ul class="ace-thumbnails clearfix">
                <!-- #section:pages/gallery -->
                @if (Model != null && Model.Any())
                {
                    foreach (var file in Model)
                    {
                        if (file.FileType.Contains("image"))
                        {
                            <li>
                                <a href="@Url.Content("~/Component/AttachmentImg/")@file.Fid" data-rel="colorbox">


                                    <img width="150" height="150" alt="150x150" src="@Url.Content("~/Component/AttachmentImg/")@file.Fid" />


                                    <div class="text">
                                        <div class="inner">@file.FileName</div>
                                    </div>
                                </a>

                                <div class="tools tools-bottom">

                                    <a href="@Url.Content("~/Component/DownloadFile/")@file.Fid">
                                        <i class="ace-icon fa fa fa-download"></i>
                                    </a>


                                </div>
                            </li>
                        }
                    }
                }
                

            </ul>
        </div>
    </div>
</div>
<div class="space-6"></div>
<div class="row">
    <div class="col-xs-12">
        <div class="message-attachment clearfix">
            <div class="attachment-title">
                <span class="blue bolder bigger-110"><fap-multilang lang-key="annex_list" default-content="附件列表"/></span>
                &nbsp;
                <span class="grey">(@fileCount <fap-multilang lang-key="files" default-content="个文件"></fap-multilang>, @Modelize MB)</span>

                <div class="inline position-relative">
                    <a href="#" data-toggle="dropdown" class="dropdown-toggle">
                        &nbsp;
                        <i class="ace-icon fa fa-caret-down bigger-125 middle"></i>
                    </a>

                    <ul class="dropdown-menu dropdown-lighter">
                        @if (bid != "")
                        {

                            <li>
                                <a href="@Url.Content("~/Component/DownloadZipFile/")@bid">
                                    <fap-multilang lang-key="download_zip" default-content="打包压缩文件下载"></fap-multilang>
                                </a>
                            </li>
                        }


                    </ul>
                </div>
            </div>
        </div>
        &nbsp;

        <ul class="attachment-list pull-left list-unstyled">
            @if (Model != null && Model.Any())
            {
                foreach (var file in Model)
                {
                    <li>
                        <a href="#" class="attached-file" data-filefid="@file.Fid" data-rel="tooltip" title="@file.FileName">
                            @if (file.FileType.Contains("image"))
                            {
                                <i class="ace-icon fa fa-file-image-o bigger-110 purple"></i>

                            }
                            else if (file.FileType.Contains("word"))
                            {
                                <i class="ace-icon fa fa-file-word-o bigger-110 blue"></i>
                            }
                            else if (file.FileType.Contains("excel"))
                            {
                                <i class="ace-icon fa fa-file-excel-o bigger-110 green"></i>
                            }
                            else
                            {
                                <i class="ace-icon fa fa-file-o bigger-110 orange"></i>
                            }
                            <span class="attached-name">@file.FileName</span>
                        </a>
                        <span class="action-buttons">
                            <a href="@Url.Content("~/Component/DownloadFile/")@file.Fid">
                                <i class="ace-icon fa fa-download bigger-125 blue"></i>
                            </a>

                            @*<a href="#" data-filefid="@file.Fid" class="deletefile">
                                <i class="ace-icon fa fa-trash-o bigger-125 red"></i>
                            </a>*@
                        </span>
                    </li>
                }
            }
            else
            {
                <li>
                    <fap-multilang lang-key="no_annex" default-content="无附件"></fap-multilang>                    
                </li>
            }

        </ul>
    </div>
</div>

product/hcm/Fap.Hcm.Web/Views/Component/DataForm.cshtml
@model Fap.AspNetCore.ViewModel.FormViewModel
@{
    Layout = null;
}
<div class="row ">
    <div class="col-xs-12">
        <div class="col-xs-12">
            <fap-form id="@Model.FormId"   form-model="Model"></fap-form>
        </div>
    </div>
</div>

product/hcm/Fap.Hcm.Web/Views/Component/EntityAssociate.cshtml
@model Fap.AspNetCore.ViewModel.JqGridViewModel

<fap-grid id="@Model.JqgridId" grid-model="Model" auto-width="true"  wrapper="modal-body" register-authority="false" oper-cud="true"></fap-grid>

product/hcm/Fap.Hcm.Web/Views/Component/EntityCondition.cshtml
@await Component.InvokeAsync("ConditionEditor", new { tableName = ViewBag.TableName })

product/hcm/Fap.Hcm.Web/Views/Component/FieldMapping.cshtml
@using Fap.AspNetCore.Controls
@model IEnumerable<Fap.Core.Infrastructure.Model.CfgEntityMapping>
@{
    List<Select2DataItem> tableList = new List<Select2DataItem>() { new Select2DataItem { Id = "", Text = "请选择" } };
    foreach (var mapping in Model)
    {
        tableList.Add(new Select2DataItem { Id = mapping.AimsEntity, Text = mapping.AimsEntityMC });
    }
}
<script>
    $(function () {
        $("#selField").select2({ width: 300, placeholder: $.lang("select_field", "选择属性"), allowClear:true });
        
    })
    //值变化事件，selEntity 触发
    var tableChange = function (e) {
        var tn= $("#sel-selEntity").val();
        if (!tn) {
            $("#selField").empty();
            return;
        }
        $.get("@Url.Content("~/Core/Api/FieldList/")" + tn, function (data) {
            if (data) {
                var filter = $.grep(data, function (d, i) {
                    return d.isDefaultCol != 1;
                })
                $("#selField").empty();
                $("#selField").append("<option></option>");
                $.each(filter, function (i, d) {
                    $("#selField").append("<option value='" + d.colName + "'>" + d.colComment + "</option>");
                })             
                $("#selField").val('');
            }
        });
    }
    function getMappingResult() {
        let dentity = $("#sel-selEntity").select2('data')[0];
        let dfield = $("#selField").select2('data')[0];
        if (dentity.id === '' || dfield.id === '') {
            return null;
        }
        return '[引用]('+dentity.text + '[' + dfield.text + '])';
    }
</script>

<div class="row">
    <div class="form-horizontal">
        <div class="form-group">
            <label class="col-sm-3 control-label no-padding-right" for="sel-selEntity">
                <fap-multilang default-content="实体" lang-key="entity"></fap-multilang>
            </label>
            <div class="col-sm-9">
                <fap-select id="selEntity" is-multi="false" placeholder="选择实体" on-change="tableChange" source-list="tableList"></fap-select>
            </div>

        </div>
        <div class="form-group">
            <label class="col-sm-3 control-label no-padding-right" for="selField">
                <fap-multilang default-content="属性" lang-key="field"></fap-multilang>
            </label>
            <div class="col-sm-9">
                <select id="selField" class="select2-allowclear tag-input-style"></select>
            </div>

        </div>
    
    </div>
</div>

product/hcm/Fap.Hcm.Web/Views/Component/FreeFormView.cshtml
@model Fap.AspNetCore.ViewModel.FormViewModel
@{
    Layout = null;
}

<div class="row scrollable frmContainer" data-size="430">
    <div class="col-xs-12">
        <div class="col-xs-12">
            <fap-freeform id="@Model.FormId" form-status="View"  form-model="Model"></fap-freeform>
        </div>
    </div>
</div>

<script src="~/lib/ueditor/ueditor.parse.js"></script>
<script>
    uParse('.frmContainer', {
        rootPath: '../'
    })
</script>

product/hcm/Fap.Hcm.Web/Views/Component/GridComponent.cshtml
@model Fap.AspNetCore.ViewModel.JqGridViewModel
@{
    Layout = null;
    string gridid = "grid-" + Model.JqgridId;
    string pagerid = "pager-" + Model.JqgridId;
    string returnfields = Model.TempData["returnfields"];
}
<script>
   
    //获取组件返回值
    var GetCompontentReturnValue=function(){
        var multi=false;
        @if (Model.IsMulti)
            {
               <text> multi = true;</text>
            }
        if(!multi)
        {
            return GetCompontentResult();
        }else {
            return GetCompontentResults();
        }
    }
    var GetRefResult=GetCompontentReturnValue;
    var GetCompontentResult = function () {
        var id = jQuery("#@gridid").jqGrid('getGridParam', 'selrow');
        if (id) {
            var ret = jQuery("#@gridid").jqGrid('getRowData', id);
            var result = {};
            @foreach (var item in returnfields.Split(','))
            {
                <text>result.@item=ret.@item;</text>
            }
            return result;
        }
        return "";
    }
    var GetCompontentResults=function() {
        var ids = jQuery("#@gridid").jqGrid('getGridParam', 'selarrrow');
        var result=[];
        if (ids) {
            for (var i = 0; i < ids.length; i++) {
                var ret = jQuery("#@gridid").jqGrid('getRowData', ids[i]);
                var selObj = {};
                @foreach (var item in returnfields.Split(','))
                {
                    <text>selObj.@item=ret.@item;</text>
                }
                result.push(selObj);
            }
        }
        return result;
    }
</script>


<div class="row">
    <div class="col-xs-12">
        <fap-grid id="@Model.JqgridId" grid-model="Model" wrapper="fapwindow" auto-width="true"  view-records="true" multi-select="@Model.IsMulti" shrink-fit="false" search-toolbar="true"></fap-grid>
    </div>
</div>

product/hcm/Fap.Hcm.Web/Views/Component/GridReference.cshtml
@model Fap.AspNetCore.ViewModel.JqGridViewModel
@{
    Layout = null;
    string frmCols = Model.TempData["frmCols"];
    string refCols = Model.TempData["refCols"];
    
}

<script>
    function GetRefResult() {
        var id = jQuery("#grid-@Model.JqgridId").jqGrid('getGridParam', 'selrow');

        if (id) {
            var ret = jQuery("#grid-@Model.JqgridId").jqGrid('getRowData', id);
            var code=ret.@Model.TempData["refid"];
            var name=ret.@Model.TempData["refname"];
            var exts = [];
            if('@refCols'!='')
            {
                var cols='@refCols'.split(',');
                for (var i = 0; i < cols.length; i++) {
                    exts.push($.trim(ret[cols[i]]));
                }
            }
            var ext=exts.join("^-^");
            var result={"code":code,"name":name,"ext":ext,"frmcols":'@frmCols' };
            return result;

        }
        return "";
    }
    function GetRefResults() {
        var ids = jQuery("#grid-@Model.JqgridId").jqGrid('getGridParam', 'selarrrow');
        var result=[];
        if (ids) {
            for (var i = 0; i < ids.length; i++) {
                var ret = jQuery("#grid-@Model.JqgridId").jqGrid('getRowData', ids[i]);
                var code=ret.@Model.TempData["refid"];
                var name=ret.@Model.TempData["refname"];
                var exts = [];
                if('@frmCols'!='')
                {
                    var cols='@frmCols'.split(',');
                    for (var i = 0; i < cols.length; i++) {
                        exts.push($.trim(ret[cols[i]]));
                    }
                }
                var ext=exts.join("^-^");
                var selObj={"code":code,"name":name,"ext":ext,"frmcols":'@frmCols'};
                result.push(selObj);
            }

            return result;

        }
        return "";
    }
    //function OnComplete()
    //{
    //    //加载树的滚动条
    //    $('.gridScrollable').ace_scroll({
    //        //styleClass: 'scroll-left scroll-margin scroll-thin scroll-dark scroll-light no-track scroll-visible'
    //        styleClass: 'scroll-top',
    //        size: $(window).innerHeight() - 240 || 400,
    //        mouseWheelLock: true,
    //        observeContent: true
    //    });
    //    setTimeout(function () {
    //        $('.treeScrollable').trigger("mouseenter.ace_scroll");
    //    }, $(window).innerHeight() - 240 || 400);
    //}
</script>

 <fap-grid id="@Model.JqgridId" grid-model="Model" auto-width="true"  height="326" search-toolbar="true" wrapper="modal-body" oper-import="false" shrink-fit="false"></fap-grid>

product/hcm/Fap.Hcm.Web/Views/Component/MultiDataGrid.cshtml
@model Fap.AspNetCore.ViewModel.MultiJqGridViewModel
@{
    int i = 0;
    int j = 0;
}
<div class="row">
    <div class="col-xs-12">
        <div class="tabbable">
            <ul class="nav nav-tabs" id="gridViewTab">
                @foreach (var keyValue in Model.JqGridViewModels)
                {
                    i++;
                    <li class="@(i==1?"active":"")">
                        <a data-toggle="tab" href="#@keyValue.Key">
                           
                            @keyValue.Value.Title
                        </a>
                    </li>

                }

            </ul>

            <div class="tab-content">
                @foreach (var keyValue in Model.JqGridViewModels)
                {
                    j++;
                    <div id="@keyValue.Key" class="tab-pane in @(j==1?"active":"")">
                        <fap-grid id="@keyValue.Value.JqgridId" grid-model="keyValue.Value" auto-width="true" view-records="true" multi-box-only="true" multi-select="true" shrink-fit="false"></fap-grid>

                    </div>

                }

            </div>
        </div>
    </div>
</div>

product/hcm/Fap.Hcm.Web/Views/Component/TreeGridReference.cshtml
@{
    Layout = null;
}

<h2>TreeGridReference</h2>